In [27]:
import numpy as np

In [28]:
np1 = np.array([1,2,3,'s1','s2',2+3,3*7,{'name':'jivesh','institute':'ARC'}])

In [29]:
np1

array([1, 2, 3, 's1', 's2', 5, 21, {'name': 'jivesh', 'institute': 'ARC'}],
      dtype=object)

In [30]:
np.min(np1)

TypeError: '<=' not supported between instances of 'int' and 'str'

In [31]:
np2 = np.array([1,2,3,4,5,6,7,8,9,10])

In [32]:
np2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
np.min(np2)

1

In [34]:
np.max(np2)

10

In [36]:
np3 = tuple(range(5,50,5))

In [37]:
np3

(5, 10, 15, 20, 25, 30, 35, 40, 45)

In [38]:
np.min(np3)

5

In [39]:
np.max(np3)

45

# making of set in numpy

In [40]:
x = np.array([[0,1,2,3,4,5],[6,7,8,9,10,11]])

In [41]:
print(f'printed set = {x}')

printed set = [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


# shape

In [42]:
y = np.shape(np1)
z = np.shape(np2)
w = np.shape(np3)
np4 = np.shape(x)

print(f'y = {y}')
print(f'z = {z}')
print(f'w = {w}')
print(f'np4 = {np4 }')

y = (8,)
z = (10,)
w = (9,)
np4 = (2, 6)


In [59]:
print(f'type(np2) = {type(np2)})

SyntaxError: unterminated string literal (detected at line 1) (2408944234.py, line 1)

In [56]:
np2 = np.array([1,2,3,4,5,6,7,8,9,10])

In [57]:
np2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
x[0,1] = 11

In [47]:
x

array([[ 0, 11,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

 # Arange
    np.arange (1,21,2)

In [52]:
array_check = np.arange(2,21,2)

In [53]:
array_check

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

# linspace

In [61]:
 a = np.linspace(0,10,15)

In [62]:
a

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [63]:
np.shape(a)

(15,)